POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImEiLCJpZCI6IjY2MWFlNTkxOGJkN2IwMTNlYWE2ZjI2NiIsImlhdCI6MTcxMzA5MjkyMX0.BXHTzCc-doC7EMakjEyJsTDQkTa3HidgjGDvrBIe9v4

{
    "title": "asdaasddas    sd",
    "author": "juuh",
    "url": "url",
    "likes": 5
}